services:
  eureka-service:
    build: ../../EurekaService
    ports:
      - "8761:8761"

  gateway-service:
    build: ../../ApiGateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
    depends_on:
      - eureka-service

  auth-service:
    build: ../../AuthService_
    ports:
      - "8084:8084"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 8463
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - eureka-service
      - db
      - kafka

  channel-service:
    build: ../../ChannelService
    ports:
      - "8085:8085"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 8463
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - eureka-service
      - db
      - kafka

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: metube
    volumes:
      - ./db-data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
