#services:
#  eureka-service:
#    image: saidaloshamsiyev1/eureka-service
#    ports:
#      - "8761:8761"
#
#  gateway-service:
#    image: saidaloshamsiyev1/gateway-service
#    ports:
#      - "8080:8080"
#    environment:
#      EUREKA_URI: http://eureka-service:8761/eureka/
#    depends_on:
#      - eureka-service
#
#
#  auth-service:
#    image: saidaloshamsiyev1/auth-service
#    ports:
#      - "8084:8084"
#    environment:
#      EUREKA_URI: http://eureka-service:8761/eureka/
#      DB_HOST: db
#      DB_USERNAME: postgres
#      DB_PASSWORD: 8463
#    depends_on:
#      - eureka-service
#      - db
#
#
#  channel-service:
#    image: saidaloshamsiyev1/channel-service
#    ports:
#      - "8085:8085"
#    environment:
#      EUREKA_URI: http://eureka-service:8761/eureka/
#      DB_HOST: db
#      DB_USERNAME: postgres
#      DB_PASSWORD: 8463
#    depends_on:
#      - eureka-service
#      - db
#
#
#
#  db:
#    image: postgres
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 8463
#      POSTGRES_DB: metube
#    volumes:
#      - ./db-data:/var/lib/postgresql/data

services:
  eureka-service:
    image: saidaloshamsiyev1/eureka-service
    ports:
      - "8761:8761"

  gateway-service:
    image: saidaloshamsiyev1/gateway-service1:5
    ports:
      - "8080:8080"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
    depends_on:
      - eureka-service

  auth-service:
    image: saidaloshamsiyev1/auth-service1:5
    ports:
      - "8084:8084"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 8463
      KAFKA_BOOTSTRAP_SERVERS: broker:29092
    depends_on:
      - eureka-service
      - db
      - broker


  channel-service:
    image: saidaloshamsiyev1/channel-service1:9
    ports:
      - "8085:8085"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 8463
      KAFKA_BOOTSTRAP_SERVERS: broker:29092  # Kafka broker ulanish manzili
    depends_on:
      - eureka-service
      - db
      - broker


  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8463
      POSTGRES_DB: metube
    volumes:
      - ./db-data:/var/lib/postgresql/data



  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "8090:8090"
    environment:
      ZOOKEEPER_CLIENT_PORT: 8090
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net

  broker:
    image: confluentinc/cp-server:7.7.1
    hostname: broker1
    container_name: broker1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:8090'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - kafka-net

  broker2:
    image: confluentinc/cp-server:7.7.1
    hostname: broker2
    container_name: broker2
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2  # Broker 2 uchun ID
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:8090'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - kafka-net

  broker3:
    image: confluentinc/cp-server:7.7.1
    hostname: broker3
    container_name: broker3
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3  # Broker 3 uchun ID
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:8090'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3:29094,PLAINTEXT_HOST://localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - kafka-net



  kafka-manager:
    image: hlebalbau/kafka-manager
    environment:
      ZK_HOSTS: zookeeper:8090
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge