services:
  eureka-service:
    image: saidaloshamsiyev1/eureka-service
    ports:
      - "8761:8761"
    networks:
      - kafka-net


  gateway-service:
    image: saidaloshamsiyev1/gateway-service1:23
    ports:
      - "8080:8080"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
    depends_on:
      - eureka-service
    networks:
      - kafka-net


  auth-service:
    image: saidaloshamsiyev1/auth-service1:32
    ports:
      - "8084:8084"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 8463
    depends_on:
      - db
      - eureka-service
    networks:
      - kafka-net


  notification-service:
    image: saidaloshamsiyev1/notification-service1:10
    ports:
      - "8087:8087"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
      KAFKA_BOOTSTRAP_SERVERS: 159.65.119.240:9092,159.65.119.240:9093,159.65.119.240:9094
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 8463
    depends_on:
      - broker
      - broker2
      - broker3
      - eureka-service
      - db
    networks:
      - kafka-net


  channel-service:
    image: saidaloshamsiyev1/channel-service1:26
    ports:
      - "8085:8085"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
      KAFKA_BOOTSTRAP_SERVERS: 159.65.119.240:9092,159.65.119.240:9093,159.65.119.240:9094
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 8463
    depends_on:
      - broker
      - broker2
      - broker3
      - eureka-service
      - db
    networks:
      - kafka-net


  interaction-service:
    image: saidaloshamsiyev1/intercation-service1:5
    ports:
      - "8088:8088"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 8463
    depends_on:
      - eureka-service
      - db
    networks:
      - kafka-net


  video-service:
    image: saidaloshamsiyev1/video-service1:2
    ports:
      - "8086:8086"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 8463
    depends_on:
      - eureka-service
      - db
    networks:
      - kafka-net


  db:
    image: postgres
    networks:
      - kafka-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8463
      POSTGRES_DB: metube
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net



  broker:
    image: confluentinc/cp-server:7.7.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://159.65.119.240:9092,PLAINTEXT_HOST://broker:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    networks:
      - kafka-net


  broker2:
    image: confluentinc/cp-server:7.7.1
    hostname: broker2
    container_name: broker2
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://159.65.119.240:9093,PLAINTEXT_HOST://broker:29093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    networks:
      - kafka-net


  broker3:
    image: confluentinc/cp-server:7.7.1
    hostname: broker3
    container_name: broker3
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://159.65.119.240:9094,PLAINTEXT_HOST://broker:29094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094,PLAINTEXT_HOST://0.0.0.0:29094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    networks:
      - kafka-net




  kafka-manager:
    image: hlebalbau/kafka-manager
    environment:
      ZK_HOSTS: zookeeper:2181
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
    networks:
      - kafka-net


networks:
  kafka-net:
    driver: bridge
