services:
  eureka-service:
    image: saidaloshamsiyev1/eureka-service
    ports:
      - "8761:8761"
    networks:
      - kafka-net


  gateway-service:
    image: saidaloshamsiyev1/gateway-service1:5
    ports:
      - "8080:8080"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
    depends_on:
      - eureka-service
    networks:
      - kafka-net


  auth-service:
    image: saidaloshamsiyev1/auth-service1:14
    ports:
      - "8084:8084"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
      KAFKA_BOOTSTRAP_SERVERS: broker:29092
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 8463
    depends_on:
      - broker
      - eureka-service
      - db
    networks:
      - kafka-net


  channel-service:
    image: saidaloshamsiyev1/channel-service1:17
    ports:
      - "8085:8085"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
      KAFKA_BOOTSTRAP_SERVERS: broker:29092
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 8463
    depends_on:
      - broker
      - eureka-service
      - db
    networks:
      - kafka-net


  db:
    image: postgres
    networks:
      - kafka-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8463
      POSTGRES_DB: metube
    volumes:
      - ./db-data:/var/lib/postgresql/data


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net



  broker:
    image: confluentinc/cp-server:7.7.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:8181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    networks:
      - kafka-net




  kafka-manager:
    image: hlebalbau/kafka-manager
    environment:
      ZK_HOSTS: zookeeper:2181
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
    networks:
      - kafka-net



networks:
  kafka-net:
    driver: bridge